# All user using this component must extends of Nomess\Component\Security\User\SecurityUser
users:
    App\Entity\User:
        # default, bcrypt, argon2i, argon2id
        algorithm: default
        request:
            # Parameters name
            identifier: _username
            password: _password
        # Error messages to return
        messages:
            missing_parameter: "Your identifier and your password is required"
            user_not_found: "You don't have account or your username is invalid"
            invalid_password: "Invalid password"

roles:
    # Role
    ROLE_USER:
        extends: []

route:
    # name of configuration
    _default:
        # Path where apply security
        path: ^/user
        # Role required
        role: ROLE_USER
        # Security will not be apply for this routes
        exclude: ^/user/login$
        # Stateless mode (required http header "Authorization: Bearer {token}")
        stateless: false
        security_dev: true
        security_prod: true
        # If is invalid credentials, redirect to ...
        redirect_to_route: user.login


token:
    private_key: '%ROOT%private.key'
    public_key: '%ROOT%public.key'
    ttl: 3600

